FROM elasticsearch:7.4.1

LABEL maintainer="Ztj <ztj1993@gmail.com>"

RUN elasticsearch-plugin install -b analysis-icu

RUN elasticsearch-plugin install -b https://dwz.cn/n6j0AbTu

RUN elasticsearch-plugin install -b https://dwz.cn/sIFiAhrP
