FROM elasticsearch:7.4.1

LABEL maintainer="Ztj <ztj1993@gmail.com>"

RUN elasticsearch-plugin install -b analysis-icu

# analysis-ik
RUN elasticsearch-plugin install -b https://dwz.cn/n6j0AbTu

# analysis-pinyin
RUN elasticsearch-plugin install -b https://dwz.cn/sIFiAhrP
